"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["application.py"]
DATA_FILES = [".env", "logo.ppm", ]
OPTIONS = {"iconfile": "appicon.icns",}

setup(
    name="Track My Pets",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
